version: '3'
services:
  main:
    image: cubeearth/cloud-tooling
    volumes:
    - $HOME/.aws:/home/user/.aws
    - ./tf-scripts:/home/user/terraform_scripts
    - ./tf-data:/home/user/terraform_data
    entrypoint:
    - /bin/sh
    - -c
    - cd /home/user/terraform_scripts;/bin/bash -l
